org: emanuelejs23
service: QUIZTOPIA-API
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}  
  iam:
    role: ${env:IAM_ROLE_ARN}  
  environment:
    USERS_TABLE: ${env:USERS_TABLE}      
    QUIZZES_TABLE: ${env:QUIZZES_TABLE}   

resources: # Aggiungi questa sezione
  Resources:
    UsersTable: # Nome della risorsa
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:USERS_TABLE} # Nome della tabella
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S # Tipo: String
        KeySchema:
          - AttributeName: username
            KeyType: HASH # Chiave primaria
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    QuizzesTable: # Nome della risorsa
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:QUIZZES_TABLE} # Nome della tabella
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S # Tipo: String
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH # Chiave primaria
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  createUser:
    handler: functions/users/createUser/index.handler
    events:
      - httpApi:
          path: /users
          method: post

  loginUser:
    handler: functions/users/loginUser/index.handler
    events:
      - httpApi:
          path: /login
          method: post

  createQuiz:
    handler: functions/quizzes/createQuiz/index.handler
    events:
      - httpApi:
          path: /quizzes
          method: post

  getQuizzes:
    handler: functions/quizzes/getQuizzes/index.handler
    events:
      - httpApi:
          path: /quizzes
          method: get

  getQuiz:
    handler: functions/quizzes/getQuiz/index.handler
    events:
      - httpApi:
          path: /quizzes/{quizId}
          method: get

  deleteQuiz:
    handler: functions/quizzes/deleteQuiz/index.handler
    events:
      - httpApi:
          path: /quizzes/{quizId}
          method: delete

  addQuestion:
    handler: functions/quizzes/addQuestion/index.handler
    events:
      - httpApi:
          path: /quizzes/{quizId}/questions
          method: post

  leaderboard:
    handler: functions/quizzes/leaderboard/index.handler
    events:
      - httpApi:
          path: /quizzes/{quizId}/leaderboard
          method: get
